openapi: '3.0.0'
info:
  title: API Boilerplate
  version: '1.0.0'
  description: API Documentation
servers:
  - url: http://localhost:3000
    description: Local development
paths: {}
components:
  securitySchemes:
    CognitoAuth:
      type: apiKey
      name: Authorization
      in: header
security:
  - CognitoAuth: [] 